/**
 * SummaryDetail - Premium Minimal Design
 * Purpose: Detailed view for AI-generated study summaries
 * Design: Material Design with full summary, key points, and actions
 */

import React, { useEffect } from 'react';
import {
  View,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  SafeAreaView,
  StatusBar,
  Share,
} from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useQuery } from '@tanstack/react-query';
import { T } from '../../ui';
import { trackScreenView, trackAction } from '../../utils/navigationAnalytics';
import { useAuth } from '../../context/AuthContext';
import { supabase } from '../../config/supabaseClient';

type Props = NativeStackScreenProps<any, 'SummaryDetail'>;

interface StudySummary {
  id: string;
  subject: string;
  topic: string;
  summary: string;
  key_points: string[];
  created_at: string;
  word_count: number;
  difficulty_level?: 'beginner' | 'intermediate' | 'advanced';
  estimated_read_time?: number;
}

export default function SummaryDetail({ route, navigation }: Props) {
  const { user } = useAuth();
  const { summaryId } = route.params || {};

  useEffect(() => {
    trackScreenView('SummaryDetail', { summaryId });
  }, [summaryId]);

  // Fetch summary details
  const { data: summary, isLoading } = useQuery({
    queryKey: ['study-summary-detail', summaryId],
    queryFn: async () => {
      if (!summaryId) throw new Error('No summary ID');

      const { data, error } = await supabase
        .from('study_summaries')
        .select('*')
        .eq('id', summaryId)
        .single();

      if (error) throw error;

      return {
        id: data.id,
        subject: data.subject || 'General',
        topic: data.topic || 'Study Topic',
        summary: data.summary || 'Summary not available',
        key_points: data.key_points || [],
        created_at: data.created_at,
        word_count: data.summary ? data.summary.split(' ').length : 0,
        difficulty_level: data.difficulty_level,
        estimated_read_time: data.estimated_read_time || Math.ceil((data.summary ? data.summary.split(' ').length : 0) / 200),
      } as StudySummary;
    },
    enabled: !!summaryId,
  });

  const getDifficultyColor = (difficulty?: string) => {
    switch (difficulty) {
      case 'beginner': return '#10B981';
      case 'intermediate': return '#F59E0B';
      case 'advanced': return '#EF4444';
      default: return '#6B7280';
    }
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const handleShare = async () => {
    if (!summary) return;

    trackAction('share_summary', 'SummaryDetail', { summaryId });

    try {
      const keyPointsText = summary.key_points.length > 0
        ? summary.key_points.map((point, i) => `${i + 1}. ${point}`).join('\n')
        : '';

      const shareContent = `📚 ${summary.topic}\n\n${summary.summary}\n\n📌 Key Points:\n${keyPointsText}\n\n- From Manushi Coaching Platform`;

      await Share.share({
        message: shareContent,
        title: summary.topic,
      });
    } catch (error) {
      console.error('Error sharing summary:', error);
    }
  };

  const handleSaveForLater = () => {
    trackAction('save_summary', 'SummaryDetail', { summaryId });
    Alert.alert(
      'Save Summary',
      'This summary has been saved to your library for quick access.',
      [{ text: 'OK' }]
    );
  };

  const handlePrintOrExport = async () => {
    if (!summary) return;

    trackAction('export_summary', 'SummaryDetail', { summaryId });

    try {
      const keyPointsText = summary.key_points.length > 0
        ? summary.key_points.map((point, i) => `${i + 1}. ${point}`).join('\n')
        : 'No key points available';

      const exportContent = `
📚 ${summary.topic}
Subject: ${summary.subject}
Date: ${formatDate(summary.created_at)}
Word Count: ${summary.word_count} words
Read Time: ${summary.estimated_read_time} minutes

━━━━━━━━━━━━━━━━━━━━━━
📝 SUMMARY:
━━━━━━━━━━━━━━━━━━━━━━

${summary.summary}

━━━━━━━━━━━━━━━━━━━━━━
📌 KEY POINTS:
━━━━━━━━━━━━━━━━━━━━━━

${keyPointsText}

━━━━━━━━━━━━━━━━━━━━━━
Generated by Manushi Coaching Platform
      `.trim();

      await Share.share({
        message: exportContent,
        title: `${summary.topic} - Study Summary`,
      });
    } catch (error) {
      console.error('Error exporting summary:', error);
      Alert.alert('Error', 'Failed to export summary. Please try again.');
    }
  };

  if (isLoading || !summary) {
    return (
      <SafeAreaView style={styles.safeArea}>
        <StatusBar barStyle="light-content" backgroundColor="#F59E0B" />
        <View style={styles.loadingContainer}>
          <T variant="body" style={styles.loadingText}>Loading summary...</T>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="light-content" backgroundColor="#F59E0B" />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <T style={styles.backIcon}>←</T>
        </TouchableOpacity>
        <T variant="h2" weight="bold" style={styles.headerTitle}>Study Summary</T>
        <TouchableOpacity
          style={styles.shareButton}
          onPress={handleShare}
          accessibilityRole="button"
          accessibilityLabel="Share summary"
        >
          <T style={styles.shareIcon}>⤴</T>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        <View style={styles.content}>
          {/* Summary Info Card */}
          <View style={styles.infoCard}>
            <View style={styles.topicRow}>
              <View style={styles.subjectBadge}>
                <T variant="caption" weight="semiBold" style={styles.subjectText}>
                  {summary.subject}
                </T>
              </View>
              {summary.difficulty_level && (
                <View
                  style={[
                    styles.difficultyBadge,
                    { backgroundColor: getDifficultyColor(summary.difficulty_level) },
                  ]}
                >
                  <T style={styles.difficultyText}>
                    {summary.difficulty_level.toUpperCase()}
                  </T>
                </View>
              )}
            </View>

            <T variant="h2" weight="bold" style={styles.topic}>
              {summary.topic}
            </T>

            <View style={styles.metaRow}>
              <View style={styles.metaItem}>
                <T variant="caption" style={styles.metaIcon}>📅</T>
                <T variant="caption" style={styles.metaText}>
                  {formatDate(summary.created_at)}
                </T>
              </View>
              <View style={styles.metaItem}>
                <T variant="caption" style={styles.metaIcon}>📄</T>
                <T variant="caption" style={styles.metaText}>
                  {summary.word_count} words
                </T>
              </View>
              <View style={styles.metaItem}>
                <T variant="caption" style={styles.metaIcon}>⏱️</T>
                <T variant="caption" style={styles.metaText}>
                  {summary.estimated_read_time} min read
                </T>
              </View>
            </View>
          </View>

          {/* Summary Content */}
          <View style={styles.summaryCard}>
            <T variant="h3" weight="bold" style={styles.sectionTitle}>Summary</T>
            <T variant="body" style={styles.summaryText}>
              {summary.summary}
            </T>
          </View>

          {/* Key Points */}
          {summary.key_points.length > 0 && (
            <View style={styles.keyPointsCard}>
              <View style={styles.keyPointsHeader}>
                <T variant="h3" weight="bold" style={styles.sectionTitle}>
                  📌 Key Points
                </T>
                <T variant="caption" style={styles.keyPointsCount}>
                  {summary.key_points.length} points
                </T>
              </View>

              {summary.key_points.map((point, index) => (
                <View key={index} style={styles.keyPointItem}>
                  <View style={styles.keyPointBullet}>
                    <T variant="caption" weight="bold" style={styles.bulletNumber}>
                      {index + 1}
                    </T>
                  </View>
                  <T variant="body" style={styles.keyPointText}>
                    {point}
                  </T>
                </View>
              ))}
            </View>
          )}

          {/* Action Buttons */}
          <View style={styles.actionsCard}>
            <TouchableOpacity
              style={styles.actionButton}
              onPress={handleSaveForLater}
              accessibilityRole="button"
              accessibilityLabel="Save summary for later"
            >
              <T style={styles.actionIcon}>📚</T>
              <T variant="body" weight="semiBold" style={styles.actionText}>
                Save for Later
              </T>
            </TouchableOpacity>

            <TouchableOpacity
              style={styles.actionButton}
              onPress={handlePrintOrExport}
              accessibilityRole="button"
              accessibilityLabel="Export or print summary"
            >
              <T style={styles.actionIcon}>📤</T>
              <T variant="body" weight="semiBold" style={styles.actionText}>
                Export / Print
              </T>
            </TouchableOpacity>
          </View>

          {/* Related Actions */}
          <TouchableOpacity
            style={styles.relatedButton}
            onPress={() => {
              trackAction('view_related_summaries', 'SummaryDetail', { subject: summary.subject });
              navigation.goBack();
            }}
            accessibilityRole="button"
          >
            <T variant="body" weight="semiBold" style={styles.relatedButtonText}>
              View More {summary.subject} Summaries →
            </T>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F59E0B',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#F59E0B',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    fontSize: 24,
    color: '#FFFFFF',
  },
  headerTitle: {
    fontSize: 20,
    color: '#FFFFFF',
  },
  shareButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareIcon: {
    fontSize: 20,
    color: '#FFFFFF',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  content: {
    padding: 16,
    paddingBottom: 32,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  topicRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  subjectBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#DBEAFE',
    borderRadius: 8,
    marginRight: 8,
  },
  subjectText: {
    color: '#1E40AF',
  },
  difficultyBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  difficultyText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  topic: {
    fontSize: 24,
    color: '#111827',
    marginBottom: 16,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaIcon: {
    fontSize: 14,
    marginRight: 4,
  },
  metaText: {
    fontSize: 12,
    color: '#6B7280',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    color: '#111827',
    marginBottom: 12,
  },
  summaryText: {
    fontSize: 16,
    color: '#374151',
    lineHeight: 26,
  },
  keyPointsCard: {
    backgroundColor: '#FEF3C7',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  keyPointsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  keyPointsCount: {
    color: '#92400E',
  },
  keyPointItem: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  keyPointBullet: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F59E0B',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  bulletNumber: {
    fontSize: 12,
    color: '#FFFFFF',
  },
  keyPointText: {
    flex: 1,
    fontSize: 15,
    color: '#78350F',
    lineHeight: 24,
  },
  actionsCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  actionText: {
    fontSize: 14,
    color: '#374151',
  },
  relatedButton: {
    backgroundColor: '#F59E0B',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  relatedButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
});
